/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package trains;

import com.sun.tools.javac.Main;
import trains.service.GraphService;
import trains.service.dto.Connection;
import trains.service.impl.GraphServiceImpl;

import java.util.Arrays;
import java.util.List;
import java.util.Optional;

public class App {

    private GraphService graphService;

    public App(GraphService graphService) {
        this.graphService = graphService;
    }

    public static void main(String[] args) {
        GraphService graphService = new GraphServiceImpl();
        App app = new App(graphService);

        // Definir las conexiones entre ciudades y sus distancias
        List<Connection> connections = Arrays.asList(
                Connection.create('A', 'B', 5),
                Connection.create('B', 'C', 4),
                Connection.create('C', 'D', 8),
                Connection.create('D', 'C', 8),
                Connection.create('D', 'E', 6),
                Connection.create('A', 'D', 5),
                Connection.create('C', 'E', 2),
                Connection.create('E', 'B', 3),
                Connection.create('A', 'E', 7)
        );

        // Consultas
        String[] queries = {"A-B-C", "A-D", "A-D-C", "A-E-B-C-D", "A-E-D"};
        graphService.calculateDistance(connections, queries);
        graphService.numberStops(connections, 'C', 'C', 3, 5);


    }
}
